In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('regression_dataset.csv')
data.head()

cases   latitude  longitude  maxtempC  ...  year  month  density_per_km  precipMM
0      2 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
1      0 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
2      1 -34.603684 -58.381559        24  ...  2016      3        0.505636       0.0
3      0 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0
4      1 -34.603684 -58.381559        22  ...  2016      4        0.505636       0.0

[5 rows x 25 columns]

In [ ]:
X = data[['maxtempC', 'mintempC', 'windspeedKmph', 'year', 'month', 'density_per_km', 'precipMM', 'cloudcover',
       'humidity','DewPointC', 'latitude', 'longitude','FeelsLikeC', 'winddirDegree', 'sunHour']]
y = data['cases']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

regressor_rf = RandomForestRegressor(n_estimators=100, random_state=10)
regressor_rf.fit(X_train, Y_train)
y_pred = regressor_rf.predict(X_test)
y_pred

array([ 0.30602381, 26.79255952,  0.        , ...,  1.5845    ,
       42.64833333, 22.44666667])

In [ ]:
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)
r2 = np.absolute(r2)
print(mse, rmse, r2)

669564.4275701249 818.2691657212343 0.37918008576550943


In [ ]:
# parameters = {'bootstrap': [True, False],
#               'max_depth': [50, 60, 70, 80, 90, 100],
#               'max_features': ['auto', 'sqrt'],
#               'min_samples_leaf': [1, 2, 4],
#               'min_samples_split': [2, 5, 10],
#               'n_estimators': [200, 400, 600, 800, 1000]}


In [ ]:
# from sklearn.model_selection import GridSearchCV

# # First create the base model to tune
# rf = RandomForestRegressor(random_state = 42)
# # Random search of parameters, using 3 fold cross validation, 
# # search across 100 different combinations, and use all available cores
# grid_search = GridSearchCV(estimator = rf, param_grid = parameters, 
#                           cv = 3, verbose = 2, return_train_score=True)

# # Fit the random search model
# grid_search.fit(X_train, Y_train);

In [ ]:
tuned_rf = RandomForestRegressor(max_depth=100, max_features='sqrt', min_samples_leaf=4, min_samples_split=10, n_estimators=1000, random_state=10)
tuned_rf.fit(X_train, Y_train)
tuned_pred = tuned_rf.predict(X_test)
tuned_pred

array([21.25409563, 64.23941036,  0.40803496, ...,  7.53035223,
       49.86970271, 15.82387342])

In [ ]:
mse = mean_squared_error(Y_test, tuned_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, tuned_pred)
r2 = np.absolute(r2)
print(mse, rmse, r2)

489745.02942980273 699.8178544662909 0.00878506067511542


In [ ]:
tuned_rf2 = RandomForestRegressor(max_depth=150, max_features='sqrt', min_samples_leaf=8, min_samples_split=16, n_estimators=1600, random_state=10)
tuned_rf2.fit(X_train, Y_train)
tuned_pred2 = tuned_rf2.predict(X_test)
tuned_pred2

array([ 29.51792543, 128.38174523,   0.55190434, ...,  12.10660172,
        58.7197974 ,  18.96214557])

In [ ]:
mse = mean_squared_error(Y_test, tuned_pred2)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, tuned_pred2)
r2 = np.absolute(r2)
print(mse, rmse, r2)

457569.3639607456 676.4387362952729 0.05749091701118281


In [ ]:
tuned_rf3 = RandomForestRegressor(max_depth=200, max_features='sqrt', min_samples_leaf=12, min_samples_split=20, n_estimators=2000, random_state=10)
tuned_rf3.fit(X_train, Y_train)
tuned_pred3 = tuned_rf3.predict(X_test)
tuned_pred3

array([ 33.18653696, 160.36971953,   0.64753662, ...,  15.54698146,
        59.89348377,  18.39258003])

In [ ]:
mse = mean_squared_error(Y_test, tuned_pred3)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, tuned_pred3)
r2 = np.absolute(r2)
print(mse, rmse, r2)

447253.55088947737 668.7701779307129 0.07873960253052015


In [ ]:
tuned_rf4 = RandomForestRegressor(max_depth=200, max_features='sqrt', min_samples_leaf=12, min_samples_split=20, n_estimators=3000, random_state=10)
tuned_rf4.fit(X_train, Y_train)
tuned_pred4 = tuned_rf4.predict(X_test)

mse = mean_squared_error(Y_test, tuned_pred4)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, tuned_pred4)
r2 = np.absolute(r2)
print(mse, rmse, r2)

447433.3663679514 668.9046018439037 0.07836921557922438


In [ ]:
tuned_rf5 = RandomForestRegressor(max_depth=300, max_features='sqrt', min_samples_leaf=16, min_samples_split=30, n_estimators=3000, random_state=10)
tuned_rf5.fit(X_train, Y_train)
tuned_pred5 = tuned_rf5.predict(X_test)

mse = mean_squared_error(Y_test, tuned_pred5)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, tuned_pred5)
r2 = np.absolute(r2)
print(mse, rmse, r2)

441754.6349246488 664.6462479580011 0.09006636225626041
